test:
  adapter: sqlite3
  database: engage_me_api_test

integration:
  adapter: sqlite3
  database: engage_me_api_integration

development:
  adapter: sqlite3
  database: engage_me_api_development

staging:
  adapter: postgresql
  database: engage_me_api_staging

production:
  adapter: postgresql
  database: engage_me_api_production