source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.0.rc1'

group :development, :test, :integration do
  gem 'sqlite3'
  gem "rspec-rails"
  gem "capybara"
  gem "factory_girl_rails", '~> 4.2.0'
  gem "foreman"
end

group :production do
  gem 'pg'
end